#!/bin/sh
# Begin $rc_base/init.d/notify

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2006-06-08 22:01:47 -0500 (Thu, 08 Jun 2006) $
#$Date: 2008-01-03  By TCB

rc_functions=/etc/rc.d/init.d/lfsfunctions
. $rc_functions
case "$1" in
	start)
		boot_mesg "Starting pserver..."
		loadproc /usr/bin/pserver
		;;

	stop)
		boot_mesg "Stopping pserver..."
		killproc /usr/bin/pserver
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;


	status)
		statusproc /usr/bin/pserver
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/notify
